# Generated by Django 2.0 on 2020-03-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NBAData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(verbose_name='排名')),
                ('ballgame', models.CharField(max_length=50, verbose_name='球隊')),
                ('win', models.IntegerField(verbose_name='勝場')),
                ('transport', models.IntegerField(verbose_name='敗場')),
                ('winrate', models.CharField(max_length=50, verbose_name='勝率')),
                ('logopath', models.ImageField(upload_to='images', verbose_name='球隊logo')),
                ('area', models.CharField(max_length=50, verbose_name='區域')),
            ],
        ),
    ]
